{
  "sksl": {
    "entrypoint": "stage_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\nuniform float uHeat;\nuniform vec3 uTop;\nuniform vec3 uBottom;\nuniform vec3 uGlow;\nuniform float uLine;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 p = FLT_flutter_local_FlutterFragCoord() / uSize;\n    float depth = p.y + (0.0599999986588954925537109375 * (1.0 - cos((p.x - 0.5) * 3.141590118408203125)));\n    vec3 col = mix(uTop, uBottom, vec3(clamp(depth, 0.0, 1.0)));\n    float breath = 0.5 + (0.5 * sin(uTime * 0.60000002384185791015625));\n    vec2 d = (p - vec2(0.5, uLine)) * vec2(1.0, 1.89999997615814208984375 - (0.4000000059604644775390625 * uHeat));\n    float pool = exp((-dot(d, d)) * (9.0 - (3.5 * uHeat)));\n    col += ((uGlow * pool) * ((0.300000011920928955078125 + (0.449999988079071044921875 * uHeat)) + (0.0599999986588954925537109375 * breath)));\n    vec2 core = (p - vec2(0.5, uLine)) * vec2(0.449999988079071044921875, 7.0);\n    col += ((uGlow * exp((-dot(core, core)) * 6.0)) * (0.20000000298023223876953125 + (0.300000011920928955078125 * uHeat)));\n    fragColor = vec4(col, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uHeat",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uTop",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uBottom",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uGlow",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uLine",
        "rows": 1,
        "type": 10
      }
    ]
  }
}