// Rebuilds lib/data/scores.g.dart from the engraved editions on the Mutopia
// Project, so the note data in this game is a machine-read copy of a published
// score rather than something typed out from memory.
//
//     dart run tool/fetch_scores.dart
//
// Needs a network connection and LilyPond on the PATH:
//
//     apt-get install -y lilypond
//
// For each score it downloads the LilyPond source, brings it up to the local
// LilyPond's syntax with convert-ly, renders MIDI with every repeat written
// out in full, and writes the bytes into a Dart file as base64. Embedding
// rather than shipping the files as assets keeps SongLibrary synchronous,
// which is what the rest of the game and its tests expect.
import 'dart:convert';
import 'dart:io';

/// A score to import, and what it takes to render it.
class _Score {
  const _Score({
    required this.constant,
    required this.url,
    required this.reference,
    required this.staffAnchor,
  });

  /// Name of the Dart constant to write.
  final String constant;

  final String url;

  /// Mutopia's own citation for the edition.
  final String reference;

  /// The text in the .ly file that opens the piano staff. `\unfoldRepeats`
  /// goes immediately before it, which is what turns the volta brackets into
  /// the notes a performer actually plays.
  final String staffAnchor;

  String get name => url.split('/').last.replaceAll('.ly', '');
}

const _scores = [
  _Score(
    constant: 'furElise',
    url: 'https://www.ibiblio.org/mutopia/ftp/BeethovenLv/WoO59/'
        'fur_Elise_WoO59/fur_Elise_WoO59.ly',
    reference: 'Mutopia-2009/08/31-931, typeset by Stelios Samelis '
        'after Breitkopf & Härtel',
    staffAnchor: r'\new PianoStaff',
  ),
  _Score(
    constant: 'preludeInC',
    url: 'https://www.mutopiaproject.org/ftp/BachJS/BWV846/'
        'wtk1-prelude1/wtk1-prelude1.ly',
    reference: 'Mutopia-2011/09/12-5, typeset by Tobias Erbsland',
    staffAnchor: r'\context PianoStaff',
  ),
];

Future<void> main() async {
  final work = await Directory.systemTemp.createTemp('piano-flow-scores');
  final rendered = <_Score, List<int>>{};

  try {
    for (final score in _scores) {
      stdout.writeln('${score.name}: downloading');
      final source = File('${work.path}/${score.name}.ly');
      await source.writeAsBytes(await _download(score.url));

      stdout.writeln('${score.name}: convert-ly');
      await _run('convert-ly', ['-e', source.path], work.path);

      // Rendering the engraving too would take far longer and produce a PDF
      // nothing here reads, so the score block is cut down to MIDI only.
      var text = await source.readAsString();
      if (!text.contains(score.staffAnchor)) {
        throw StateError('${score.name}: no "${score.staffAnchor}" to unfold '
            'repeats around — the upstream file has changed shape');
      }
      text = text.replaceFirst(
          score.staffAnchor, r'\unfoldRepeats ' + score.staffAnchor);
      text = text.replaceAll(RegExp(r'\\layout\s*\{\s*\}'), '');
      await source.writeAsString(text);

      stdout.writeln('${score.name}: lilypond');
      await _run('lilypond',
          ['-dno-point-and-click', '-o', score.name, source.path], work.path);

      final midi = File('${work.path}/${score.name}.midi');
      if (!midi.existsSync()) {
        throw StateError('${score.name}: LilyPond produced no MIDI');
      }
      rendered[score] = await midi.readAsBytes();
      stdout.writeln('${score.name}: ${rendered[score]!.length} bytes');
    }
  } finally {
    await work.delete(recursive: true);
  }

  final out = StringBuffer()
    ..writeln('// GENERATED BY tool/fetch_scores.dart — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Standard MIDI files rendered from the LilyPond sources on')
    ..writeln('// the Mutopia Project, with every repeat written out in full.')
    ..writeln('// The music is public domain and the engravings are released')
    ..writeln('// into the public domain by their typesetters.')
    ..writeln('//')
    ..writeln('// Run the tool again to refresh them.')
    ..writeln('library;')
    ..writeln();

  for (final entry in rendered.entries) {
    out
      ..writeln('/// ${entry.key.url}')
      ..writeln('///')
      ..writeln('/// ${entry.key.reference}.')
      ..writeln('const String ${entry.key.constant} =');
    final encoded = base64.encode(entry.value);
    for (var i = 0; i < encoded.length; i += 72) {
      final chunk = encoded.substring(i, (i + 72).clamp(0, encoded.length));
      final last = i + 72 >= encoded.length;
      out.writeln("    '$chunk'${last ? ';' : ''}");
    }
    out.writeln();
  }

  final target = File('lib/data/scores.g.dart');
  await target.writeAsString(out.toString());
  stdout.writeln('wrote ${target.path}');
}

Future<List<int>> _download(String url) async {
  final client = HttpClient();
  try {
    final request = await client.getUrl(Uri.parse(url));
    final response = await request.close();
    if (response.statusCode != 200) {
      throw HttpException('HTTP ${response.statusCode} for $url');
    }
    return [await for (final chunk in response) ...chunk];
  } finally {
    client.close();
  }
}

Future<void> _run(String executable, List<String> args, String cwd) async {
  final result = await Process.run(executable, args, workingDirectory: cwd);
  if (result.exitCode != 0) {
    stderr.writeln(result.stdout);
    stderr.writeln(result.stderr);
    throw ProcessException(executable, args, 'failed', result.exitCode);
  }
}
